trigger:
  batch: true
  branches:
    include:
      - "main"

variables:
- name: SolutionBaseName
  value: SFA.DAS.FAA
- name: BuildConfiguration
  value: release
- name: BuildPlatform
  value: any cpu
- group: RELEASE Management Resources
- group: RELEASE das-findapprenticeship-web
- name: Deploy
  value: $[or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), eq(variables['Build.Reason'], 'Manual'), eq(variables['Build.Reason'], 'PullRequest'))]

resources:
  repositories:
  - repository: self
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/tags/2.1.28
    endpoint: SkillsFundingAgency
  - repository: das-platform-automation
    type: github
    name: SkillsFundingAgency/das-platform-automation
    ref: refs/tags/5.1.8
    endpoint: SkillsFundingAgency
  pipelines:
  - pipeline: das-employer-config
    project: Digital Apprenticeship Service
    source: das-employer-config
    branch: master

stages:
- stage: Build
  jobs:
  - template: pipeline-templates/job/code-build.yml
    parameters:
      SolutionBaseName: $(SolutionBaseName)
      BuildConfiguration: $(BuildConfiguration)

- stage: Deploy_AT
  dependsOn: Build
  displayName: Deploy to AT
  condition: and(succeeded(), eq(variables.Deploy, 'true'))
  variables:
  - group: DevTest Management Resources
  - group: AT DevTest Shared Resources
  jobs:
  - template: pipeline-templates/job/deploy.yml
    parameters:
      Environment: AT
      SolutionBaseName: $(SolutionBaseName)
      ServiceConnection: SFA-DAS-DevTest-ARM

- stage: Test_AT
  dependsOn: Deploy_AT
  displayName: Test AT Environment
  variables:
  - group: DevTest Management Resources
  jobs:
  - template: pipeline-templates/job/environment-test.yml
    parameters:
      BuildConfiguration: $(BuildConfiguration)
      SolutionBaseName: $(SolutionBaseName)
      Environment: at

- stage: Deploy_TEST
  dependsOn: Build
  displayName: Deploy to TEST
  variables:
  - group: DevTest Management Resources
  - group: TEST DevTest Shared Resources
  - group: TEST das-findapprenticeship-web
  jobs:
  - template: pipeline-templates/job/deploy.yml
    parameters:
      Environment: TEST
      SolutionBaseName: $(SolutionBaseName)
      ServiceConnection: SFA-DAS-DevTest-ARM

# - stage: Test_TEST
#   dependsOn: Deploy_TEST
#   displayName: Test TEST Environment
#   variables:
#   - group: DevTest Management Resources
#   jobs:
#   - template: pipeline-templates/job/environment-test.yml
#     parameters:
#       BuildConfiguration: $(BuildConfiguration)
#       SolutionBaseName: $(SolutionBaseName)
#       Environment: test

- stage: Deploy_TEST2
  dependsOn: Build
  displayName: Deploy to TEST2
  variables:
  - group: DevTest Management Resources
  - group: TEST2 DevTest Shared Resources
  - group: TEST2 das-findapprenticeship-web
  jobs:
  - template: pipeline-templates/job/deploy.yml
    parameters:
      Environment: TEST2
      SolutionBaseName: $(SolutionBaseName)
      ServiceConnection: SFA-DAS-DevTest-ARM

# - stage: Test_TEST2
#   dependsOn: Deploy_TEST2
#   displayName: Test TEST2 Environment
#   variables:
#   - group: DevTest Management Resources
#   jobs:
#   - template: pipeline-templates/job/environment-test.yml
#     parameters:
#       BuildConfiguration: $(BuildConfiguration)
#       SolutionBaseName: $(SolutionBaseName)
#       Environment: TEST2

- stage: Deploy_PP
  dependsOn: Build
  displayName: Deploy to PP
  variables:
  - group: PreProd Management Resources
  - group: PreProd Shared Resources
  - group: PreProd das-findapprenticeship-web
  jobs:
  - template: pipeline-templates/job/deploy.yml
    parameters:
      Environment: PP
      SolutionBaseName: $(SolutionBaseName)
      ServiceConnection: SFA-DIG-PreProd-ARM

# - stage: Test_PP
#   dependsOn: Deploy_PP
#   displayName: Test PP Environment
#   variables:
#   - group: PreProd Management Resources
#   jobs:
#   - template: pipeline-templates/job/environment-test.yml
#     parameters:
#       BuildConfiguration: $(BuildConfiguration)
#       SolutionBaseName: $(SolutionBaseName)
#       Environment: pp

- stage: Deploy_PROD
  dependsOn: Build
  displayName: Deploy to PROD
  variables:
  - group: PROD Management Resources
  - group: PROD Shared Resources
  - group: PROD das-findapprenticeship-web
  jobs:
  - template: pipeline-templates/job/deploy.yml
    parameters:
      Environment: PROD
      SolutionBaseName: $(SolutionBaseName)
      ServiceConnection: SFA-DIG-Prod-ARM

# - stage: Test_PROD
#   dependsOn: Deploy_PROD
#   displayName: Test PROD Environment
#   variables:
#   - group: PROD Management Resources
#   jobs:
#   - template: pipeline-templates/job/environment-test.yml
#     parameters:
#       BuildConfiguration: $(BuildConfiguration)
#       SolutionBaseName: $(SolutionBaseName)
#       Environment: prod

- stage: Deploy_MO
  dependsOn: Build
  displayName: Deploy to MO
  variables:
  - group: MO Management Resources
  - group: MO Shared Resources
  jobs:
  - template: pipeline-templates/job/deploy.yml
    parameters:
      Environment: MO
      SolutionBaseName: $(SolutionBaseName)
      ServiceConnection: SFA-ASM-ModelOffice-ARM

# - stage: Test_MO
#   dependsOn: Deploy_MO
#   displayName: Test MO Environment
#   variables:
#   - group: MO Management Resources
#   jobs:
#   - template: pipeline-templates/job/environment-test.yml
#     parameters:
#       BuildConfiguration: $(BuildConfiguration)
#       SolutionBaseName: $(SolutionBaseName)
#       Environment: mo

- stage: Deploy_DEMO
  dependsOn: Build
  displayName: Deploy to DEMO
  variables:
  - group: DevTest Management Resources
  - group: DEMO DevTest Shared Resources
  - group: DEMO das-findapprenticeship-web
  jobs:
  - template: pipeline-templates/job/deploy.yml
    parameters:
      Environment: DEMO
      SolutionBaseName: $(SolutionBaseName)
      ServiceConnection: SFA-DAS-DevTest-ARM

# - stage: Test_DEMO
#   dependsOn: Deploy_DEMO
#   displayName: Test DEMO Environment
#   variables:
#   - group: DevTest Management Resources
#   jobs:
#   - template: pipeline-templates/job/environment-test.yml
#     parameters:
#       BuildConfiguration: $(BuildConfiguration)
#       SolutionBaseName: $(SolutionBaseName)
#       Environment: demo
