parameters:
  SolutionBaseName: ''
  BuildConfiguration: 'Release'

jobs:
- job: CodeBuild
  pool:
    name: DAS - Continuous Integration Agents
    workspace:
      clean: all
  variables:
  - group: BUILD Management Resources

  steps:
  - template: azure-pipelines-templates/build/step/gitversion.yml@das-platform-building-blocks

  - template: azure-pipelines-templates/build/step/app-build.yml@das-platform-building-blocks
    parameters:
      ContinueOnVulnerablePackageScanError: true

  - task: DotNetCoreCLI@2
    displayName: Restore Dependencies
    inputs:
      command: restore
      projects: src/SFA.DAS.FAA.Web.AcceptanceTests/SFA.DAS.FAA.Web.AcceptanceTests.csproj

  - task: DotNetCoreCLI@2
    displayName: Build Acceptance Tests
    inputs:
      command: build
      projects: src/SFA.DAS.FAA.Web.AcceptanceTests/SFA.DAS.FAA.Web.AcceptanceTests.csproj
      arguments: '--configuration ${{ parameters.BuildConfiguration }}'

  - task: DotNetCoreCLI@2
    displayName: Publish Acceptance Tests
    inputs:
      command: publish
      projects: src/SFA.DAS.FAA.Web.AcceptanceTests/SFA.DAS.FAA.Web.AcceptanceTests.csproj
      arguments: '--configuration ${{ parameters.BuildConfiguration }} -o $(build.artifactstagingdirectory)/acceptance-tests'

  - task: PublishPipelineArtifact@1
    displayName: Publish Build Artifacts
    inputs:
      targetPath: $(build.artifactstagingdirectory)
      artifactName: ${{ parameters.SolutionBaseName }}
