global using NUnit.Framework;
global using Moq;
global using FluentAssertions;
global using FluentAssertions.Execution;
global using AutoFixture;
global using AutoFixture.NUnit3;
global using SFA.DAS.Testing.AutoFixture;
global using FluentValidation;
global using FluentValidation.Results;